services:
  frontend:
    image: kamilox25/front-ev2:latest
    container_name: flask-frontend
    restart: always
    ports:
      - "80:5000"
    env_file:
      - .env
    volumes:
      - frontend_data:/app/data
      - frontend_logs:/app/logs
    networks:
      - app-network

volumes:
  frontend_data:
    driver: local
  frontend_logs:
    driver: local

networks:
  app-network:
    external: true