services:
  frontend:
    # Cambiamos 'build: .' por la imagen que ya tienes en tu PC
    image: kamilox25/front-ev2:latest 
    container_name: flask-frontend
    restart: always
    ports:
      - "80:5000"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    external: true