
name: Publicar imagen docker
#Para compatibilidad con Node 24 en acciones de JavaScript
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:
      - deploy
      - main

# Definición del trabajo para construir y publicar la imagen Docker
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo del repo
        uses: actions/checkout@v4

      - name: Iniciar sesion en Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/front-ev2:latest

      - name: Verificar conectividad SSH a EC2
        run: |
          echo "Host objetivo: ${{ secrets.EC2_HOST }}"
          nc -vz -w 5 ${{ secrets.EC2_HOST }} 22

      # --- DESPLIEGUE AUTOMÁTICO EN EC2 ---
      # Este paso se conecta por SSH a tu instancia EC2 y actualiza el contenedor frontend automáticamente.
     

      - name: Desplegar en EC2 vía SSH
        uses: appleboy/ssh-action@v1.0.3  # Acción para ejecutar comandos SSH desde GitHub Actions
        with:
          host: ${{ secrets.EC2_HOST }}         # IP pública o DNS de tu EC2
          username: ec2-user                    # Usuario por defecto en Amazon Linux
          key: ${{ secrets.EC2_SSH_KEY }}       # Llave privada SSH (agrega como secreto en GitHub)
          port: 22                              # Puerto SSH por defecto
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/front-ev2:latest
            docker rm -f flask-frontend || true
            docker run -d --name flask-frontend --network app-network --env-file /home/ec2-user/Front_Eval2/.env -p 80:5000 ${{ secrets.DOCKER_USERNAME }}/front-ev2:latest
      

    